import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Assignment Advisor',
  description: 'Generated by create next app',
  icons: {
    icon: '/cap.png', 
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/cap.png" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
